POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker 2"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/33d0d497-4a7d-4f2c-abb0-7cd583942bb6