POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Novo curso"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/7c467c89-89b7-4e7d-9309-e9c7dd1b944c